version: '3.8'

volumes:
  pg_data:

services:
  db:
    image: postgres:15
    env_file:
      - .env
    container_name: wallet_db
    volumes:
      - ./pg_data:/var/lib/postgresql/data
    ports:
      - 5432:5432

  app:
    build:
      context: .
    depends_on:
      - db
    container_name: wallet
    env_file:
      - .env
    ports:
      - '8000:8000'
    command: sh -c "alembic upgrade head && uvicorn main:app --host 0.0.0.0 --port 8000"
